import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to anon,authenticated,service_role;`);
for(const file of ['supabase-setup.sql','migrations/001_multi_club.sql','migrations/002_meeting_minutes_times.sql','migrations/003_attendance.sql'])await db.exec((await readFile(file,'utf8')).replace('create extension if not exists pgcrypto;',''));
const ids=Array.from({length:4},(_,i)=>`00000000-0000-4000-8000-00000000000${i+1}`);
for(const id of ids)await db.query(`insert into auth.users(id,email_confirmed_at,raw_user_meta_data) values($1,now(),'{"first_name":"Test","last_initial":"T"}')`,[id]);
const club=(await db.query("select id from clubs where legacy_key='bsu'")).rows[0].id;
const other=(await db.query("insert into clubs(name) values('Other') returning id")).rows[0].id;
await db.query("insert into club_memberships values($1,$2,'officer',now()),($1,$3,'member',now()),($1,$4,'member',now()),($5,$6,'officer',now())",[club,ids[0],ids[1],ids[2],other,ids[3]]);
async function as(id,sql,args=[]){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec(id?'set role authenticated':'set role anon');try{return (await db.query(sql,args)).rows;}finally{await db.exec('reset role');}}
const event=(await db.query("insert into events(club_id,name,event_date,location) values($1,'Now',now(),'Room') returning id",[club])).rows[0].id;
const later=(await db.query("insert into events(club_id,name,event_date,location) values($1,'Later',now()+interval '2 hours','Room') returning id",[club])).rows[0].id;
const action=(id,kind,e=event)=>as(id,'select event_action($1,$2)',[e,kind]);
for(const id of [null,ids[1],ids[3]])await assert.rejects(()=>action(id,'start'));
await assert.rejects(()=>action(ids[0],'start',later));
await assert.rejects(()=>action(ids[1],'check_in'));
await action(ids[0],'start');await assert.rejects(()=>action(ids[0],'start'));
await assert.rejects(()=>action(ids[3],'check_in'));
await action(ids[1],'check_in');await action(ids[1],'check_in');await action(ids[2],'check_in');
assert.equal((await db.query('select count(*)::int n from attendance')).rows[0].n,2);
assert.equal((await as(ids[1],'select * from attendance')).length,1);
assert.equal((await as(ids[0],'select * from attendance')).length,2);
assert.equal((await as(ids[3],'select * from attendance')).length,0);
await assert.rejects(()=>as(ids[1],'insert into attendance(event_id,user_id) values($1,$2)',[later,ids[2]]));
await assert.rejects(()=>as(ids[1],"update event_sessions set actual_end_time=now()"));
for(const id of [null,ids[1],ids[3]])await assert.rejects(()=>as(id,'select club_officer_report($1)',[club]));
assert.equal((await as(ids[1],'select club_activity($1) r',[club]))[0].r.attended,0);
assert.equal((await as(ids[1],'select club_activity($1) r',[club]))[0].r.sessions[0].attendee_count,undefined);
assert.equal((await as(ids[0],'select club_activity($1) r',[club]))[0].r.sessions[0].attendee_count,2);
await action(ids[0],'end');await assert.rejects(()=>action(ids[2],'check_in'));await assert.rejects(()=>action(ids[0],'end'));
await as(ids[0],"select event_action($1,'edit',now()-interval '2 hours',now()-interval '1 hour')",[event]);
await assert.rejects(()=>as(ids[0],"select event_action($1,'edit',now(),now()-interval '1 hour')",[event]));
await assert.rejects(()=>as(ids[0],"select event_action($1,'edit',now(),null)",[event]));
const stats=(await as(ids[0],'select club_officer_report($1) r',[club]))[0].r;
assert.equal(stats.events_held,1);assert.equal(stats.event_minutes,60);assert.equal(stats.average_attendance,2);assert.equal(stats.check_ins,2);assert.equal(stats.total_members,3);
assert.equal((await as(ids[1],'select club_activity($1) r',[club]))[0].r.attended,1);
const empty=(await as(ids[3],'select club_officer_report($1) r',[other]))[0].r;assert.equal(empty.average_attendance,0);
assert.equal((await as(ids[1],'select * from profiles')).length,1);
console.log('PASS: attendance migration, start window, officer scope, private records/directory, duplicate check-in, completed-event rejection, corrected duration, private totals, and empty stats. No Auth emails or signup tests executed.');
await db.close();
