import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to anon,authenticated,service_role; grant execute on function auth.uid() to public;`);
const users = Array.from({length:5},(_,i)=>`00000000-0000-4000-8000-00000000000${i+1}`);
for(const id of users) await db.query('insert into auth.users(id,email_confirmed_at) values($1,now())',[id]);
await db.exec((await readFile('supabase-setup.sql','utf8')).replace('create extension if not exists pgcrypto;',''));
await db.query(`insert into admins(user_id) values($1)`,[users[1]]);
const legacy=(await db.query(`insert into events(name,event_type,event_date,location) values('Original meeting','meeting',now(),'Original room') returning id,created_at`)).rows[0];
await db.query(`insert into event_officer_details(event_id,notes,secretary_notes) values($1,'Original agenda','Original secretary notes')`,[legacy.id]);
const migrationSql=await readFile('migrations/001_multi_club.sql','utf8');
await db.exec(migrationSql);
console.log('Migration applies to an existing single-club schema.');
for (const table of ['events','announcements','club_settings','event_officer_details','admins']) {
  const before=(await db.query('select records from private.legacy_bsu_snapshot where source_table=$1',[table])).rows[0].records;
  const after=(await db.query(`select coalesce(jsonb_agg(to_jsonb(t)-'club_id'),'[]') records from public.${table} t`)).rows[0].records;
  assert.deepEqual(after,before,`${table}: migration must preserve original columns and timestamps exactly`);
}
const a=(await db.query("select id from clubs where legacy_key='bsu'")).rows[0].id;
assert.equal((await db.query('select name from events where id=$1',[legacy.id])).rows[0].name,'Original meeting');
assert.equal((await db.query('select secretary_notes from meeting_agenda_items where meeting_id=$1',[legacy.id])).rows[0].secretary_notes,'Original secretary notes');
assert.equal((await db.query('select count(*)::int n from app_admins')).rows[0].n,0);
await db.query('insert into app_admins(user_id) values($1)',[users[0]]);
async function asUser(id,sql,params=[]) {await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec(id?'set role authenticated':'set role anon');try{return await db.query(sql,params);}finally{await db.exec('reset role');}}
async function denied(id,sql,params=[]) {await assert.rejects(()=>asUser(id,sql,params));}
const b=(await asUser(users[0],"select create_club('Second Club','Test club') id")).rows[0].id;
await db.query("insert into club_memberships(club_id,user_id,role) values($1,$2,'member'),($3,$2,'officer'),($1,$4,'member')",[a,users[2],b,users[3]]);
const second=(await asUser(users[2],"insert into events(club_id,name,event_type,event_date,location) values($1,'B meeting','meeting',now(),'Room B') returning id",[b])).rows[0].id;
assert.equal((await asUser(users[1],'select * from events where club_id=$1',[b])).rows.length,0);
assert.equal((await asUser(users[1],"update events set name='Stolen' where id=$1 returning id",[second])).rows.length,0);
await denied(users[1],"insert into events(club_id,name,event_date,location) values($1,'No',now(),'No')",[b]);
await denied(users[2],"insert into events(club_id,name,event_date,location) values($1,'No',now(),'No')",[a]);
await denied(users[1],'select create_club($1,$2)',['Unauthorized','']);
await denied(users[1],'select delete_club($1,$2)',[b,'Second Club']);
await denied(users[1],"insert into app_admins(user_id) values($1)",[users[1]]);
await denied(users[2],"update club_memberships set role='officer' where club_id=$1",[a]);
await denied(null,'select * from events');
assert.equal((await asUser(users[3],'select * from meeting_agenda_items')).rows.length,0);
await denied(users[3],'select get_club_codes($1)',[a]);
await denied(users[1],'select get_club_codes($1)',[b]);
const codes=(await asUser(users[1],'select get_club_codes($1) codes',[a])).rows[0].codes;
// Exercise actual RLS for each content table, not just hidden UI controls.
const announcement=(await asUser(users[1],"insert into announcements(club_id,title,body) values($1,'Officer update','Body') returning id",[a])).rows[0].id;
for(const id of [users[2],users[3]]) {
  assert.equal((await asUser(id,"update events set name='Forbidden' where id=$1 returning id",[legacy.id])).rows.length,0);
  assert.equal((await asUser(id,"update announcements set title='Forbidden' where id=$1 returning id",[announcement])).rows.length,0);
  assert.equal((await asUser(id,"update club_settings set club_name='Forbidden' where club_id=$1 returning club_id",[a])).rows.length,0);
  await denied(id,'select create_club($1,$2)',['No','']);await denied(id,'select delete_club($1,$2)',[a,'Black Student Union']);
}
await denied(users[1],"select regenerate_club_code($1,'officer')",[b]);
await denied(users[1],"update events set club_id=$1 where id=$2",[b,legacy.id]);
await denied(null,"insert into events(club_id,name,event_date,location) values($1,'No',now(),'No')",[a]);
await denied(null,'select get_club_codes($1)',[a]);
await denied(null,'select * from private.club_access_codes');
await denied(users[1],'select * from private.legacy_bsu_snapshot');
await asUser(users[1],"update announcements set body='Edited' where id=$1",[announcement]);
await asUser(users[1],"update club_settings set club_name='Black Student Union',color_scheme='sunset' where club_id=$1",[a]);
await asUser(users[1],'delete from announcements where id=$1',[announcement]);
assert.match(codes.member,/^MEM-\d{3}-\d{3}$/);assert.match(codes.officer,/^OFI-\d{3}-\d{3}$/);
async function redeem(code,kind,user,ip='test-ip'){await db.exec('set role service_role');try{return (await db.query('select redeem_club_code($1,$2,$3,$4) r',[code,kind,user,ip])).rows[0].r;}finally{await db.exec('reset role');}}
await denied(users[3],'select redeem_club_code($1,$2,$3,$4)',[codes.officer,'officer',users[3],'forged']);
assert.ok((await redeem(codes.officer,'member',null)).error);
const guest=await redeem(codes.member,'member',null);
assert.equal(guest.club_id,a);
const guestData=(await asUser(null,'select guest_club_data($1) d',[guest.guest_token])).rows[0].d;
assert.equal(guestData.club.id,a);assert.equal(guestData.events.length,1);assert.ok(!JSON.stringify(guestData).includes('Original agenda'));
await denied(null,'select guest_club_data($1)',['fake']);
await redeem(codes.officer,'officer',users[3]);await redeem(codes.member,'member',users[3]);
assert.equal((await db.query('select role from club_memberships where club_id=$1 and user_id=$2',[a,users[3]])).rows[0].role,'officer');
await asUser(users[1],"select regenerate_club_code($1,'member')",[a]);
assert.ok((await redeem(codes.member,'member',null)).error);
await denied(null,'select guest_club_data($1)',[guest.guest_token]);
assert.equal((await db.query('select count(*)::int n from club_memberships where club_id=$1 and user_id=$2',[a,users[3]])).rows[0].n,1);
const newCodes=(await asUser(users[1],'select get_club_codes($1) codes',[a])).rows[0].codes;
assert.equal((await redeem(newCodes.member.toLowerCase(),'member',users[4],'new-member')).club_id,a);
const rotatedOfficer=(await asUser(users[1],"select regenerate_club_code($1,'officer') code",[a])).rows[0].code;
assert.ok((await redeem(codes.officer,'officer',users[4],'new-officer')).error);
assert.equal((await redeem(rotatedOfficer,'officer',users[4],'new-officer')).club_id,a);
assert.equal((await redeem(rotatedOfficer,'officer',users[4],'new-officer')).already_officer,true);
assert.equal((await db.query('select count(*)::int n from club_memberships where club_id=$1 and user_id=$2',[a,users[4]])).rows[0].n,1);
for(let i=0;i<12;i++) await redeem('MEM-xxx','member',null,'rate-test');
assert.equal((await redeem('MEM-xxx','member',null,'rate-test')).error,'rate_limited');
const version=(await db.query('select updated_at from events where id=$1',[legacy.id])).rows[0].updated_at;
const points=[{id:crypto.randomUUID(),title:'First',talking_point:'Discuss',secretary_notes:'Private answer'},{id:crypto.randomUUID(),title:'Second',talking_point:'Review',secretary_notes:''}];
await denied(users[2],'select save_meeting_agenda($1,$2,$3)',[legacy.id,JSON.stringify(points),version]);
const saved=(await asUser(users[1],'select save_meeting_agenda($1,$2,$3) version',[legacy.id,JSON.stringify(points),version])).rows[0].version;
await denied(users[1],'select save_meeting_agenda($1,$2,$3)',[legacy.id,JSON.stringify(points),version]);
await asUser(users[1],'select save_meeting_agenda($1,$2,$3)',[legacy.id,JSON.stringify(points.reverse()),saved]);
assert.equal((await db.query('select title from meeting_agenda_items where meeting_id=$1 order by sort_order',[legacy.id])).rows[0].title,'Second');
const current=(await db.query('select updated_at from events where id=$1',[legacy.id])).rows[0].updated_at;
await denied(users[1],'select save_meeting_agenda($1,$2,$3)',[legacy.id,JSON.stringify([points[0],points[0]]),current]);
assert.equal((await db.query('select count(*)::int n from meeting_agenda_items where meeting_id=$1',[legacy.id])).rows[0].n,2);
await asUser(users[1],'select save_meeting_agenda($1,$2,$3)',[legacy.id,JSON.stringify([points[0]]),current]);
assert.equal((await db.query('select count(*)::int n from meeting_agenda_items where meeting_id=$1',[legacy.id])).rows[0].n,1);
const freshUser=crypto.randomUUID();await db.query(`insert into auth.users(id,raw_user_meta_data) values($1,'{"first_name":"New","last_initial":"n","role":"officer"}')`,[freshUser]);
assert.equal((await asUser(freshUser,'select first_name,last_initial from profiles')).rows[0].last_initial,'N');
assert.equal((await asUser(freshUser,'select * from club_memberships')).rows.length,0);
await asUser(users[0],'select delete_club($1,$2)',[b,'Second Club']);
assert.equal((await db.query('select count(*)::int n from events where club_id=$1',[b])).rows[0].n,0);
assert.equal((await db.query('select count(*)::int n from auth.users')).rows[0].n,6);
assert.equal((await db.query('select count(*)::int n from events where club_id=$1',[a])).rows[0].n,1);
console.log('PASS: BSU preservation, no automatic Super Admin, multi-club RLS, member/officer isolation, guest scope, code formats/rotation/rate limits, upgrades, atomic agendas/concurrency, scoped deletion.');
await assert.rejects(()=>db.exec(migrationSql),/already applied/);
await db.exec('rollback');
await db.close();
